package com.ashok.ddqs.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of BUYER.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Buyer implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** BUYER_ID. */
	private Integer buyerId;

	/** BUYER_NAME. */
	private String buyerName;

	/** BUYER_DETAILS. */
	private String buyerDetails;

	/** TRADER. */
	private Trader trader;

	/** The set of QUESTIONAIR. */
	private Set<Questionair> questionairSet;

	/**
	 * Constructor.
	 */
	public Buyer() {
		this.questionairSet = new HashSet<Questionair>();
	}

	/**
	 * Set the BUYER_ID.
	 * 
	 * @param buyerId
	 *            BUYER_ID
	 */
	public void setBuyerId(Integer buyerId) {
		this.buyerId = buyerId;
	}

	/**
	 * Get the BUYER_ID.
	 * 
	 * @return BUYER_ID
	 */
	public Integer getBuyerId() {
		return this.buyerId;
	}

	/**
	 * Set the BUYER_NAME.
	 * 
	 * @param buyerName
	 *            BUYER_NAME
	 */
	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	/**
	 * Get the BUYER_NAME.
	 * 
	 * @return BUYER_NAME
	 */
	public String getBuyerName() {
		return this.buyerName;
	}

	/**
	 * Set the BUYER_DETAILS.
	 * 
	 * @param buyerDetails
	 *            BUYER_DETAILS
	 */
	public void setBuyerDetails(String buyerDetails) {
		this.buyerDetails = buyerDetails;
	}

	/**
	 * Get the BUYER_DETAILS.
	 * 
	 * @return BUYER_DETAILS
	 */
	public String getBuyerDetails() {
		return this.buyerDetails;
	}

	/**
	 * Set the TRADER.
	 * 
	 * @param trader
	 *            TRADER
	 */
	public void setTrader(Trader trader) {
		this.trader = trader;
	}

	/**
	 * Get the TRADER.
	 * 
	 * @return TRADER
	 */
	public Trader getTrader() {
		return this.trader;
	}

	/**
	 * Set the set of the QUESTIONAIR.
	 * 
	 * @param questionairSet
	 *            The set of QUESTIONAIR
	 */
	public void setQuestionairSet(Set<Questionair> questionairSet) {
		this.questionairSet = questionairSet;
	}

	/**
	 * Add the QUESTIONAIR.
	 * 
	 * @param questionair
	 *            QUESTIONAIR
	 */
	public void addQuestionair(Questionair questionair) {
		this.questionairSet.add(questionair);
	}

	/**
	 * Get the set of the QUESTIONAIR.
	 * 
	 * @return The set of QUESTIONAIR
	 */
	public Set<Questionair> getQuestionairSet() {
		return this.questionairSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((buyerId == null) ? 0 : buyerId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Buyer other = (Buyer) obj;
		if (buyerId == null) {
			if (other.buyerId != null) {
				return false;
			}
		} else if (!buyerId.equals(other.buyerId)) {
			return false;
		}
		return true;
	}

}
