package com.ashok.ddqs.model;

import java.io.Serializable;

/**
 * Model class of OPTIONS.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Options implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** OPTION_ID. */
	private Integer optionId;

	/** IS_MSMC. */
	private String isMsmc;

	/** IS_SSMC. */
	private String isSsmc;

	/** IS_BOOLEAN. */
	private String isBoolean;

	/** IS_TEXT. */
	private String isText;

	/** OPTION_TEXT. */
	private String optionText;

	/** QUESTIONS. */
	private Questions questions;

	/**
	 * Constructor.
	 */
	public Options() {
	}

	/**
	 * Set the OPTION_ID.
	 * 
	 * @param optionId
	 *            OPTION_ID
	 */
	public void setOptionId(Integer optionId) {
		this.optionId = optionId;
	}

	/**
	 * Get the OPTION_ID.
	 * 
	 * @return OPTION_ID
	 */
	public Integer getOptionId() {
		return this.optionId;
	}

	/**
	 * Set the IS_MSMC.
	 * 
	 * @param isMsmc
	 *            IS_MSMC
	 */
	public void setIsMsmc(String isMsmc) {
		this.isMsmc = isMsmc;
	}

	/**
	 * Get the IS_MSMC.
	 * 
	 * @return IS_MSMC
	 */
	public String getIsMsmc() {
		return this.isMsmc;
	}

	/**
	 * Set the IS_SSMC.
	 * 
	 * @param isSsmc
	 *            IS_SSMC
	 */
	public void setIsSsmc(String isSsmc) {
		this.isSsmc = isSsmc;
	}

	/**
	 * Get the IS_SSMC.
	 * 
	 * @return IS_SSMC
	 */
	public String getIsSsmc() {
		return this.isSsmc;
	}

	/**
	 * Set the IS_BOOLEAN.
	 * 
	 * @param isBoolean
	 *            IS_BOOLEAN
	 */
	public void setIsBoolean(String isBoolean) {
		this.isBoolean = isBoolean;
	}

	/**
	 * Get the IS_BOOLEAN.
	 * 
	 * @return IS_BOOLEAN
	 */
	public String getIsBoolean() {
		return this.isBoolean;
	}

	/**
	 * Set the IS_TEXT.
	 * 
	 * @param isText
	 *            IS_TEXT
	 */
	public void setIsText(String isText) {
		this.isText = isText;
	}

	/**
	 * Get the IS_TEXT.
	 * 
	 * @return IS_TEXT
	 */
	public String getIsText() {
		return this.isText;
	}

	/**
	 * Set the OPTION_TEXT.
	 * 
	 * @param optionText
	 *            OPTION_TEXT
	 */
	public void setOptionText(String optionText) {
		this.optionText = optionText;
	}

	/**
	 * Get the OPTION_TEXT.
	 * 
	 * @return OPTION_TEXT
	 */
	public String getOptionText() {
		return this.optionText;
	}

	/**
	 * Set the QUESTIONS.
	 * 
	 * @param questions
	 *            QUESTIONS
	 */
	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	/**
	 * Get the QUESTIONS.
	 * 
	 * @return QUESTIONS
	 */
	public Questions getQuestions() {
		return this.questions;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((optionId == null) ? 0 : optionId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Options other = (Options) obj;
		if (optionId == null) {
			if (other.optionId != null) {
				return false;
			}
		} else if (!optionId.equals(other.optionId)) {
			return false;
		}
		return true;
	}

}
