package com.ashok.ddqs.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of QUESTIONS.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Questions implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** QUESTION_ID. */
	private Integer questionId;

	/** QUESTION_TEXT. */
	private String questionText;

	/** QUESTIONAIR. */
	private Questionair questionair;

	/** The set of OPTIONS. */
	private Set<Options> optionsSet;

	/**
	 * Constructor.
	 */
	public Questions() {
		this.optionsSet = new HashSet<Options>();
	}

	/**
	 * Set the QUESTION_ID.
	 * 
	 * @param questionId
	 *            QUESTION_ID
	 */
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	/**
	 * Get the QUESTION_ID.
	 * 
	 * @return QUESTION_ID
	 */
	public Integer getQuestionId() {
		return this.questionId;
	}

	/**
	 * Set the QUESTION_TEXT.
	 * 
	 * @param questionText
	 *            QUESTION_TEXT
	 */
	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	/**
	 * Get the QUESTION_TEXT.
	 * 
	 * @return QUESTION_TEXT
	 */
	public String getQuestionText() {
		return this.questionText;
	}

	/**
	 * Set the QUESTIONAIR.
	 * 
	 * @param questionair
	 *            QUESTIONAIR
	 */
	public void setQuestionair(Questionair questionair) {
		this.questionair = questionair;
	}

	/**
	 * Get the QUESTIONAIR.
	 * 
	 * @return QUESTIONAIR
	 */
	public Questionair getQuestionair() {
		return this.questionair;
	}

	/**
	 * Set the set of the OPTIONS.
	 * 
	 * @param optionsSet
	 *            The set of OPTIONS
	 */
	public void setOptionsSet(Set<Options> optionsSet) {
		this.optionsSet = optionsSet;
	}

	/**
	 * Add the OPTIONS.
	 * 
	 * @param options
	 *            OPTIONS
	 */
	public void addOptions(Options options) {
		this.optionsSet.add(options);
	}

	/**
	 * Get the set of the OPTIONS.
	 * 
	 * @return The set of OPTIONS
	 */
	public Set<Options> getOptionsSet() {
		return this.optionsSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((questionId == null) ? 0 : questionId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Questions other = (Questions) obj;
		if (questionId == null) {
			if (other.questionId != null) {
				return false;
			}
		} else if (!questionId.equals(other.questionId)) {
			return false;
		}
		return true;
	}

}
