package com.ashok.ddqs.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of QUESTIONAIR.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Questionair implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** QUESTIONAIR_ID. */
	private Integer questionairId;

	/** BUYER. */
	private Buyer buyer;

	/** The set of QUESTIONS. */
	private Set<Questions> questionsSet;

	/** The set of RESPONSE. */
	private Set<Response> responseSet;

	/** The set of VENDOR. */
	private Set<Vendor> vendorSet;

	/**
	 * Constructor.
	 */
	public Questionair() {
		this.questionsSet = new HashSet<Questions>();
		this.responseSet = new HashSet<Response>();
		this.vendorSet = new HashSet<Vendor>();
	}

	/**
	 * Set the QUESTIONAIR_ID.
	 * 
	 * @param questionairId
	 *            QUESTIONAIR_ID
	 */
	public void setQuestionairId(Integer questionairId) {
		this.questionairId = questionairId;
	}

	/**
	 * Get the QUESTIONAIR_ID.
	 * 
	 * @return QUESTIONAIR_ID
	 */
	public Integer getQuestionairId() {
		return this.questionairId;
	}

	/**
	 * Set the BUYER.
	 * 
	 * @param buyer
	 *            BUYER
	 */
	public void setBuyer(Buyer buyer) {
		this.buyer = buyer;
	}

	/**
	 * Get the BUYER.
	 * 
	 * @return BUYER
	 */
	public Buyer getBuyer() {
		return this.buyer;
	}

	/**
	 * Set the set of the QUESTIONS.
	 * 
	 * @param questionsSet
	 *            The set of QUESTIONS
	 */
	public void setQuestionsSet(Set<Questions> questionsSet) {
		this.questionsSet = questionsSet;
	}

	/**
	 * Add the QUESTIONS.
	 * 
	 * @param questions
	 *            QUESTIONS
	 */
	public void addQuestions(Questions questions) {
		this.questionsSet.add(questions);
	}

	/**
	 * Get the set of the QUESTIONS.
	 * 
	 * @return The set of QUESTIONS
	 */
	public Set<Questions> getQuestionsSet() {
		return this.questionsSet;
	}

	/**
	 * Set the set of the RESPONSE.
	 * 
	 * @param responseSet
	 *            The set of RESPONSE
	 */
	public void setResponseSet(Set<Response> responseSet) {
		this.responseSet = responseSet;
	}

	/**
	 * Add the RESPONSE.
	 * 
	 * @param response
	 *            RESPONSE
	 */
	public void addResponse(Response response) {
		this.responseSet.add(response);
	}

	/**
	 * Get the set of the RESPONSE.
	 * 
	 * @return The set of RESPONSE
	 */
	public Set<Response> getResponseSet() {
		return this.responseSet;
	}

	/**
	 * Set the set of the VENDOR.
	 * 
	 * @param vendorSet
	 *            The set of VENDOR
	 */
	public void setVendorSet(Set<Vendor> vendorSet) {
		this.vendorSet = vendorSet;
	}

	/**
	 * Add the VENDOR.
	 * 
	 * @param vendor
	 *            VENDOR
	 */
	public void addVendor(Vendor vendor) {
		this.vendorSet.add(vendor);
	}

	/**
	 * Get the set of the VENDOR.
	 * 
	 * @return The set of VENDOR
	 */
	public Set<Vendor> getVendorSet() {
		return this.vendorSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((questionairId == null) ? 0 : questionairId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Questionair other = (Questionair) obj;
		if (questionairId == null) {
			if (other.questionairId != null) {
				return false;
			}
		} else if (!questionairId.equals(other.questionairId)) {
			return false;
		}
		return true;
	}

}
