package com.ashok.ddqs.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Model class of USER.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "USER_TABLE")
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** USER_ID. */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long userId;

	/** USER_NAME. */
	@Column
	private String userName;

	/** PASSWORD. */
	@Column
	private String password;

	/** USER_ROLE. */
	@Column
	private String userRole;

	/** TRADER. */
	/*@Column
	private Trader trader;*/

	/**
	 * Constructor.
	 */
	public User() {
	}

	/**
	 * Set the USER_ID.
	 * 
	 * @param userId
	 *            USER_ID
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * Get the USER_ID.
	 * 
	 * @return USER_ID
	 */
	public Long getUserId() {
		return this.userId;
	}

	/**
	 * Set the USER_NAME.
	 * 
	 * @param userName
	 *            USER_NAME
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Get the USER_NAME.
	 * 
	 * @return USER_NAME
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * Set the PASSWORD.
	 * 
	 * @param password
	 *            PASSWORD
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the PASSWORD.
	 * 
	 * @return PASSWORD
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the USER_ROLE.
	 * 
	 * @param userRole
	 *            USER_ROLE
	 */
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	/**
	 * Get the USER_ROLE.
	 * 
	 * @return USER_ROLE
	 */
	public String getUserRole() {
		return this.userRole;
	}

	/**
	 * Set the TRADER.
	 * 
	 * @param trader
	 *            TRADER
	 */
	/*public void setTrader(Trader trader) {
		this.trader = trader;
	}

	*//**
	 * Get the TRADER.
	 * 
	 * @return TRADER
	 *//*
	public Trader getTrader() {
		return this.trader;
	}*/

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (userId == null) {
			if (other.userId != null) {
				return false;
			}
		} else if (!userId.equals(other.userId)) {
			return false;
		}
		return true;
	}

}
