package com.ashok.ddqs.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of VENDOR.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Vendor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** VENDOR_ID. */
	private Integer vendorId;

	/** VENDOR_NAME. */
	private String vendorName;

	/** VENDOR_DETAILS. */
	private String vendorDetails;

	/** TRADER. */
	private Trader trader;

	/** QUESTIONAIR. */
	private Questionair questionair;

	/** The set of RESPONSE. */
	private Set<Response> responseSet;

	/**
	 * Constructor.
	 */
	public Vendor() {
		this.responseSet = new HashSet<Response>();
	}

	/**
	 * Set the VENDOR_ID.
	 * 
	 * @param vendorId
	 *            VENDOR_ID
	 */
	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	/**
	 * Get the VENDOR_ID.
	 * 
	 * @return VENDOR_ID
	 */
	public Integer getVendorId() {
		return this.vendorId;
	}

	/**
	 * Set the VENDOR_NAME.
	 * 
	 * @param vendorName
	 *            VENDOR_NAME
	 */
	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	/**
	 * Get the VENDOR_NAME.
	 * 
	 * @return VENDOR_NAME
	 */
	public String getVendorName() {
		return this.vendorName;
	}

	/**
	 * Set the VENDOR_DETAILS.
	 * 
	 * @param vendorDetails
	 *            VENDOR_DETAILS
	 */
	public void setVendorDetails(String vendorDetails) {
		this.vendorDetails = vendorDetails;
	}

	/**
	 * Get the VENDOR_DETAILS.
	 * 
	 * @return VENDOR_DETAILS
	 */
	public String getVendorDetails() {
		return this.vendorDetails;
	}

	/**
	 * Set the TRADER.
	 * 
	 * @param trader
	 *            TRADER
	 */
	public void setTrader(Trader trader) {
		this.trader = trader;
	}

	/**
	 * Get the TRADER.
	 * 
	 * @return TRADER
	 */
	public Trader getTrader() {
		return this.trader;
	}

	/**
	 * Set the QUESTIONAIR.
	 * 
	 * @param questionair
	 *            QUESTIONAIR
	 */
	public void setQuestionair(Questionair questionair) {
		this.questionair = questionair;
	}

	/**
	 * Get the QUESTIONAIR.
	 * 
	 * @return QUESTIONAIR
	 */
	public Questionair getQuestionair() {
		return this.questionair;
	}

	/**
	 * Set the set of the RESPONSE.
	 * 
	 * @param responseSet
	 *            The set of RESPONSE
	 */
	public void setResponseSet(Set<Response> responseSet) {
		this.responseSet = responseSet;
	}

	/**
	 * Add the RESPONSE.
	 * 
	 * @param response
	 *            RESPONSE
	 */
	public void addResponse(Response response) {
		this.responseSet.add(response);
	}

	/**
	 * Get the set of the RESPONSE.
	 * 
	 * @return The set of RESPONSE
	 */
	public Set<Response> getResponseSet() {
		return this.responseSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((vendorId == null) ? 0 : vendorId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Vendor other = (Vendor) obj;
		if (vendorId == null) {
			if (other.vendorId != null) {
				return false;
			}
		} else if (!vendorId.equals(other.vendorId)) {
			return false;
		}
		return true;
	}

}
